---

- name: Boot to Console
  command: systemctl set-default multi-user.target
  command: ln -fs /lib/systemd/system/getty@.service /etc/systemd/system/getty.target.wants/getty@tty1.service

- name: Copy fdisk resize script
  copy: src=fdisk dest=/root/fdisk.sh mode=755
  register: fdisk

- name: run fdisk
  shell: /root/fdisk.sh
  when: fdisk.changed
  ignore_errors: yes

- name: expandfs
  command: resize2fs /dev/mmcblk0p2
  notify: reboot
  when: fdisk.changed

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=2 timeout=300
  sudo: false
  when: fdisk.changed

- name: Copy and run raspi-init
  copy: src=raspi-init.sh dest=/root/raspi-init.sh mode=755
  register: raspi-init

- name: raspi init
  shell: /root/raspi-init.sh
  when: raspi-init.changed

- name: Install list of packages
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
       - omxplayer
       - mailutils
       - scrot
       - lighttpd
       - ca-certificates
       - rpi-update
- name: Run rpi-update
  command: rpi-update

- name: Copy configuration files.
  copy: src=autostart dest=/etc/xdg/lxsession/LXDE-pi/autostart

- name: Copy configuration files.
  copy: src=lightdm dest=/etc/lightdm/lightdm.conf

- name: Copy configuration files.
  copy: src=notifyPi dest=/etc/network/if-up.d/notifyPi mode=755

- name: Copy configuration files.
  copy: src={{item}} dest=/boot/{{item}} mode=755
  with_items:
       - config.txt
       - cmdline.txt

- name: Copy configuration files.
  copy: src=rc.local dest=/etc/rc.local mode=755

- name: Download Video
  get_url: url={{ video_url }} dest=/root/video-file
  notify: reboot


...
