---

- name: Boot to Console
  command: systemctl set-default multi-user.target
  command: ln -fs /lib/systemd/system/getty@.service /etc/systemd/system/getty.target.wants/getty@tty1.service

- name: Copy fdisk resize script
  copy: src=fdisk dest=/root/fdisk.sh mode=755
  register: fdisk

- name: run fdisk
  shell: /root/fdisk.sh
  when: fdisk.changed
  async: 1
  poll: 0
  sudo: true
  ignore_errors: yes

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=15 connect_timeout=2 timeout=300
  sudo: false
  when: fdisk.changed

- name: expandfs
  command: resize2fs /dev/mmcblk0p2

- name: Copy and run raspi-init
  copy: src=raspi-init.sh dest=/root/raspi-init.sh mode=755
  register: raspi

- name: raspi init
  shell: /root/raspi-init.sh
  when: raspi.changed

- name: Install list of packages
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
       - omxplayer
       - mailutils
       - scrot
       - lighttpd
       - ca-certificates
       - rpi-update
       - libsasl2-modules
       - postfix

- name: Run rpi-update
  command: rpi-update

- name: Creates ssl private directory
  file:  path=/etc/ssl/private/ state=directory mode=755 owner=root group=root

- name: Generate SelfSigned SSL for STARTTLS Options
  command: openssl req -new -x509 -days 3650 -nodes -out /etc/ssl/certs/postfix.pem -keyout /etc/ssl/private/postfix.pem -subj "/CN={{ ansible_fqdn|lower }}" creates=/etc/ssl/private/postfix.pem

- name: Set Permissions for Certificate
  file: path=/etc/ssl/certs/postfix.pem owner=root group=root mode=0400

- name: Set Permissions for Private Key
  file: path=/etc/ssl/private/postfix.pem owner=root group=root mode=0400

- name: configure postfix
  template: src={{item}}.j2 dest=/etc/postfix/{{item}}
  with_items:
    - recipient_canonical_map
    - generic
    - main.cf
    - sasl_passwd
  notify:
    - reload postfix
    - postmap sasl_passwd

- name: Setup script to alert on server boot
  template: src=boot-notify.j2 dest=/etc/init.d/boot-notify mode=0755

- name: Ensure that the boot notify script runs at boot
  service: name=boot-notify enabled=yes

- name: Copy configuration files.
  copy: src={{item}} dest=/boot/{{item}} mode=755
  with_items:
       - cmdline.txt

- name: template configuration files.
  template: src=config.j2 dest=/boot/config.txt mode=755

- name: Copy configuration files.
  copy: src=rc.local dest=/etc/rc.local mode=755

- name: Download Video
  get_url: url={{ video_url }} dest=/root/video-file force=yes
  notify: reboot


...
